language: generic 
sudo: required
services:
  - docker
before_install:
  - docker build -t carlosarantes/react-com-docker -f Dockerfile.dev .
script:
  - docker run -e CI=true carlosarantes/react-com-docker npm run test  